# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      #run: dotnet build --no-restore
    # - name: Test
    #  run: dotnet test --no-build --verbosity normal
      run: dotnet build --configuration Release --no-restore
    - name: Pack project
      run: dotnet pack ./descarga-ciec-csharp/descarga-ciec-csharp.csproj --configuration Release --output --no-restore ./nupkg
    - name: Publish the NuGet package
      if: github.event_name == 'release'
      env: 
       NUGET_API_KEY: ${ secrets.NUGET_API_KEY }
       run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
