on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Generate and publish new version'
        required: true
        default: 'No'
        type: choice
        options:
        - No
        - Yes
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
